### ISSUE TITLE
New Account Highlighter Mappings are stuck at 2022-04-18

### ISSUE THREAD

**Issue by iProdigy** [FrankerFaceZ/Add-Ons#115]
https://ffz.0x.bot/api/mappings.json seems to not be updating since 2022-04-18, resulting in the new account time thresholds not being properly adhered to.

@1F916

**Comment by 1F916** [comment]
This should be working again since 2022-05-21. 

The problem occurs approximately once a year because of the incredibly sloppy way the timestamp to userid association is cached by my backend service. Said caching exists in an effort to avoid repeatedly hitting the Twitch API in a loop while generating the mappings file.
When this happens, I just manually clear the cache and the service runs fine again for another year.

I will surely™️ get around to implement a permanent fix for this at some point. For the time being though, I just happened upon this issue and cleared the cache. So we should be good for another year or so from the date of this comment.

**Comment by iProdigy** [comment]
Confirmed fixed, thanks @1F916 !
