### ISSUE TITLE
[Deck] column sort option

### ISSUE THREAD

**Issue by CopperFig** [FrankerFaceZ/Add-Ons#254]
Add Option to sort every column individually
Like view count, time live, category, ...

**Comment by SirStendec** [comment]
The available sorting options are limited to the sorting options we can request from the server. I do not intend to implement custom sorting on columns that can load additional data, as that would lead to a terrible user experience of needing to scroll back to the start and re-read everything every time new data loads. I am also not going to just pre-load a ton of data for that situation because that would create unnecessary load on Twitch's service.
