### ISSUE TITLE
BetterTTV Emotes gifs are static in clips

### ISSUE THREAD

**Issue by Eyebqll** [FrankerFaceZ/Add-Ons#55]
example: https://www.youtube.com/watch?v=IdLIFF5LlmM

**Comment by eugenern** [comment]
I experience this same issue. I think it only occurs for me if my BTTV extension is enabled at the same time, but I generally have it enabled because I prefer its tab-completion to FFZ's. This issue can also be worked around by disabling BTTV Emotes in FFZ's Add-On settings, but that of course causes BTTV emotes not to appear in FFZ-related UIs like its emote menu or colon tab-completion (which I do use for a different purpose than unprefixed tab-completion).

**Comment by SirStendec** [comment]
There is a setting to control emote animation in Chat > Appearance >> Emotes. By default, animation is disabled. However, if BetterTTV is detected, it tries to use the value of BetterTTV's GIF Emotes setting.

In either case, please make sure your Animated Emotes setting is set to Enabled if you wish to see the animations.

Let me know if you have that set to Enabled but you still see the static images, please.

**Comment by Eyebqll** [comment]
i had animated emotes enabled but when i disabled and enabled it, it started working agian. i also had bttv enabled

**Comment by Lordmau5** [comment]
Closed under the assumption that this is fixed
