### ISSUE TITLE
Anonymous/lurker chat

### ISSUE THREAD

**Issue by pointydev** [FrankerFaceZ/Add-Ons#79]
Noticed over time that quite a few people have asked about anon chat implementations for FFZ in various places, and I'm aware that this isn't something for core FFZ, so guess I'll put it here (since it was one of the few things that didn't have feature parity when I switched from BTTV fully).

The feature would allow you to connect to chat in a state similar to if you were viewing a stream while logged out, only logging you in once you actually send a message. This is useful if you like lurking in streams while not getting called out, either by chatters or bots. BTTV's implementation also supports manually parting and joining via chat commands, regardless of the setting.

* [BTTV's current implementation](https://github.com/night/betterttv/blob/07146981ab22c15971d9183c5d11f0e2d4796f0c/src/modules/anon_chat/index.js)
* FrankerFaceZ/FrankerFaceZ#301
* FrankerFaceZ/FrankerFaceZ#1052
* ~~*the many messages in discord that ask about this*~~

Thanks,
Elliott

**Comment by Lordmau5** [comment]
Closing this in favor of FrankerFaceZ/FrankerFaceZ#301 and FrankerFaceZ/FrankerFaceZ#1052.

My last info on this is that Stendec isn't too fond of us messing with the chat connection since it can end up causing issues.

If someone would like to make an external FFZ add-on (similar to how The FFZ Enhancing Add-On does it as it's own browser extension that utilizes FFZ's add-on system) then they are free to do so, but having it listed on the official FFZ add-on repository doesn't seem like an option right now.

Maybe this'll change in the future though.

**Comment by pointydev** [comment]
> having it listed on the official FFZ add-on repository doesn't seem like an option right now

It could be an option to leave this issue open to attract attention from budding add-on developers (especially since the other two linked issues are closed too), but have any "released" add-on be unlisted in this official repository, with the assumption that people going to the length of looking up an add-on's ID understand the possible consequences of enabling something that messes with the chat connection.
