### ISSUE TITLE
[Pronouns] Fast Chat Networking Issues

### ISSUE THREAD

**Issue by SirStendec** [FrankerFaceZ/Add-Ons#81]
When chat receives a burst of messages from new users, the pronouns extension in its current form creates a flood of `fetch()` requests, leading to connection issues with other parts of Twitch such as videos and emotes loading.

To solve this, I plan on implementing a throttle to only look up a certain number of users at once.

Is it possible to look up users in a batch @Alejo47 ? I understand if you want to keep it to single users per request for caching, just curious before I dig into fixing the issue.

**Comment by Alejo47** [comment]
There used to be a single endpoint that would return all users, but that was removed to prevent harassment and also because it was a huge payload, I don't have any plans for batch requests at the moment, but if I have some time, I could potentially work on it. I was planning on a big refactor which would take some time before it is ready, but I could get that endpoint in there.

**Comment by SirStendec** [comment]
Closed by 4226814aeb402f557393d43d1a9b28e4d79b5436
